server:
 forward-headers-strategy: framework
 port: 8080

spring:
 mvc:
  pathmatch:
   matching-strategy: ant_path_matcher
 data:
  elasticsearch:
    repositories:
     enabled: true

 elasticsearch:
  uris: http://localhost:9200
#  path-prefix: book
#  password: password
#  username: user
